export { Home } from './Home'
export { AboutMe } from './AboutMe'
export { Portfolio } from './Portfolio'
export { Resume } from './Resume'
export { Classes } from './Classes'
export { Contact } from './Contact'
export { NoMatch } from './NoMatch'