export { Card } from './Card'
export type { CardProps } from './Card'
export { NavBar } from './NavBar'
export { Footer } from './Footer'
export { Section } from './Section'
export { TecnologyRect } from './TecnologyRect'
export { NavBarLink } from './NavBarLink'
export { CustomAnchor } from './CustomAnchor'